In [11]:
import kNN
"""
group, labels = kNN.createDataSet()
print "group is ", group
print "labels are ", labels
kNN.classify0([0,0], group, labels, 3)
"""
normMat, ranges, minVals = kNN.autoNorm()


group is  [[ 1.   1.1]
 [ 1.   1. ]
 [ 0.   0. ]
 [ 0.   0.1]]
labels are  ['A', 'A', 'B', 'B']
tile(inX, (dataSetSize, 1)) is  [[0 0]
 [0 0]
 [0 0]
 [0 0]]
diffMat is :  [[-1.  -1.1]
 [-1.  -1. ]
 [ 0.   0. ]
 [ 0.  -0.1]]
sqDiffMat is :  [[ 1.    1.21]
 [ 1.    1.  ]
 [ 0.    0.  ]
 [ 0.    0.01]]
sqDistances is :  [ 2.21  2.    0.    0.01]
sortedDistIndicies is :  [2 3 1 0]
This is 0 time, voteIlabel is : B 
This is 0 time, classCount[voteIlabel]  is : 1 
This is 1 time, voteIlabel is : B 
This is 1 time, classCount[voteIlabel]  is : 2 
This is 2 time, voteIlabel is : A 
This is 2 time, classCount[voteIlabel]  is : 1 
classCount is  {'A': 1, 'B': 2}
This is the sortedClassCount :  [('B', 2), ('A', 1)]


'B'

In [16]:
from numpy import *
import matplotlib.pyplot as plt
import kNN

def file2matrix(filename):
    fr = open(filename,'r')
    arrayOlines = fr.readlines()
    numberOfLines = len(arrayOlines)
    returnMat = zeros((numberOfLines,3)) #构造全零阵来存放数
    classLabelVector = [] #开辟容器
    index = 0

    for line in arrayOlines:
        #清洗数据
        line = line.strip()
        listFromLine = line.split('\t')
        #将评价转化为数字
        if listFromLine[3] == 'largeDoses':
            listFromLine[3] =3
        elif listFromLine[3] == 'smallDoses':
            listFromLine[3]=2
        else:
            listFromLine[3]=1
        #存入数据到list
        returnMat[index,:] = listFromLine[0:3] #三个特征分别存入一行的三个列
        classLabelVector.append(int(listFromLine[3])) #最后一行是类别标签

        index +=1
    return returnMat,classLabelVector
datingDataMat, datingLabels = file2matrix('datingTestSet.txt')
normMat, ranges, minVals = kNN.autoNorm()
normMat

"""
test = datingDataMat[0:6]
print test
print test[:,1]
print test[:, 2]
"""

"""
#将喜欢强度转化为颜色
def ColorOfDatingLable(num):
    datingLabels_rgb = []
    for i in range(len(num)):
        if num[i]==3:
            datingLabels_rgb.append('red')
        elif num[i]==2:
            datingLabels_rgb.append('green')
        else:
            datingLabels_rgb.append('black')

    return datingLabels_rgb

##################创建图表1#####################
plt.figure(1) #创建图表1

ax1 = plt.subplot(1,2,1) # 图表1中创建子图1
plt.title("original color")
plt.xlabel('play game/time %')
plt.ylabel('ice cream cost/week')

ax2 = plt.subplot(1,2,2) # 图表1中创建子图2
plt.title("improved color")
plt.xlabel('play game/time %')
plt.ylabel('ice cream cost/week')

###################创建图表2####################
plt.figure(2) #创建图表2

ax3 = plt.subplot(2,2,1) # 图表2中创建子图1
plt.title("play game & ice cream cost")
plt.xlabel('play game/time %')
plt.ylabel('ice cream cost/week')

ax4 = plt.subplot(2,2,2) # 图表2中创建子图2
plt.title("fly distance & play game")
plt.xlabel('fly distance/year')
plt.ylabel('play game/time %')

ax5 = plt.subplot(2,2,3) # 图表2中创建子图2
plt.title("fly distance & ice cream cost")
plt.xlabel('fly distance/year')
plt.ylabel('ice cream cost/week')

#plt.scatter(x[i],y[i],marker = 样式,s=大小半径,color =(np.random.rand(1,3)),label = str(i+1))
ax1.scatter(datingDataMat[:,1],datingDataMat[:,2],15*array(datingLabels),15*array(datingLabels)) #scatter散点图展示第二列和第三列数据
ax2.scatter(datingDataMat[:,1],datingDataMat[:,2],s=15*array(datingLabels),color=ColorOfDatingLable(datingLabels)) #scatter散点图展示第二列和第三列数据,第一个15*array(datingLabels)用来表现不同标签的不同半径
ax3.scatter(datingDataMat[:,1],datingDataMat[:,2],s=15*array(datingLabels),color=ColorOfDatingLable(datingLabels),label='largeDoses/smallDoses/didntLike')
ax4.scatter(datingDataMat[:,0],datingDataMat[:,1],s=15*array(datingLabels),color=ColorOfDatingLable(datingLabels),label='largeDoses/smallDoses/didntLike')
ax5.scatter(datingDataMat[:,0],datingDataMat[:,2],s=15*array(datingLabels),color=ColorOfDatingLable(datingLabels),label='largeDoses/smallDoses/didntLike')

ax3.legend(loc='upper right')
ax4.legend(loc='upper right')
ax5.legend(loc='upper right')

plt.close('all')
#plt.show()
"""


TypeError: autoNorm() takes exactly 1 argument (0 given)

In [ ]:
from numpy import *
import matplotlib.pyplot as plt
import kNN

def file2matrix(filename):
    fr = open(filename,'r')
    arrayOlines = fr.readlines()
    numberOfLines = len(arrayOlines)
    returnMat = zeros((numberOfLines,3)) #构造全零阵来存放数
    classLabelVector = [] #开辟容器
    index = 0

    for line in arrayOlines:
        #清洗数据
        line = line.strip()
        listFromLine = line.split('\t')
        #将评价转化为数字
        if listFromLine[3] == 'largeDoses':
            listFromLine[3] =3
        elif listFromLine[3] == 'smallDoses':
            listFromLine[3]=2
        else:
            listFromLine[3]=1
        #存入数据到list
        returnMat[index,:] = listFromLine[0:3] #三个特征分别存入一行的三个列
        classLabelVector.append(int(listFromLine[3])) #最后一行是类别标签

        index +=1
    return returnMat,classLabelVector
datingDataMat, datingLabels = file2matrix('datingTestSet.txt')
normMat, ranges, minVals = kNN.autoNorm(datingDataMat)

kNN.datingClassTest()


 normMat.shape is:  (1000, 3)
tile(inX, (dataSetSize, 1)) is  [[ 0.44832535  0.39805139  0.56233353]
 [ 0.44832535  0.39805139  0.56233353]
 [ 0.44832535  0.39805139  0.56233353]
 ..., 
 [ 0.44832535  0.39805139  0.56233353]
 [ 0.44832535  0.39805139  0.56233353]
 [ 0.44832535  0.39805139  0.56233353]]
diffMat is :  [[ 0.14282427 -0.02525585  0.22620209]
 [ 0.32574803  0.08018452  0.24181329]
 [-0.17393972  0.20845061  0.06110976]
 ..., 
 [ 0.15716587 -0.11105154  0.0515386 ]
 [-0.07878562 -0.03860311  0.13332873]
 [-0.03108258  0.0212423  -0.22338451]]
sqDiffMat is :  [[ 0.02039877  0.00063786  0.05116739]
 [ 0.10611178  0.00642956  0.05847366]
 [ 0.03025503  0.04345166  0.0037344 ]
 ..., 
 [ 0.02470111  0.01233245  0.00265623]
 [ 0.00620717  0.0014902   0.01777655]
 [ 0.00096613  0.00045124  0.04990064]]
sqDistances is :  [ 0.07220402  0.171015    0.07744108  0.39529964  0.32598333  0.3838722
  0.26481627  0.41605496  0.4026227   0.16569651  0.28762164  0.1908163
  0.23011528  0.1265